 Array Creation
 Create a 1D NumPy array with elements ranging from 0 to 9.
 Create a 3x3 NumPy array filled with the value 7.

In [32]:
import numpy as np

array_1d = np.arange(10)
print("1D Array:", array_1d)
array_3x3_seven = np.full((3, 3), 7)
print("3x3 Array filled with 7:\n", array_3x3_seven)


1D Array: [0 1 2 3 4 5 6 7 8 9]
3x3 Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


 Array Operations
 Create two 2D arrays of shape (3, 3) and perform element-wise addition and
multiplication.
 Create a 4x4 array of random integers between 10 and 50. Find the maximum and
minimum values in the array.

In [33]:
array_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

addition_result = array_a + array_b
multiplication_result = array_a * array_b

print("Element-wise Addition:\n", addition_result)
print("Element-wise Multiplication:\n", multiplication_result)

array_random = np.random.randint(10, 51, (4, 4))
max_value = np.max(array_random)
min_value = np.min(array_random)

print("4x4 Array of random integers:\n", array_random)
print("Maximum value:", max_value)
print("Minimum value:", min_value)


Element-wise Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
4x4 Array of random integers:
 [[27 16 14 26]
 [26 16 28 43]
 [11 44 50 33]
 [22 28 21 22]]
Maximum value: 50
Minimum value: 11


 Indexing and Slicing
 Create a 5x5 array of sequential numbers starting from 1. Extract the middle 3x3 sub-
array.
 Given a 2D array of shape (4, 4), set all elements in the first row to 0

In [35]:
array_sequential = np.arange(1, 26).reshape(5, 5)
middle_sub_array = array_sequential[1:4, 1:4]

print("5x5 Array of sequential numbers:\n", array_sequential)
print("Middle 3x3 Sub-array:\n", middle_sub_array)
array_4x4 = np.random.randint(1, 10, (4, 4))
array_4x4[0, :] = 0

print("2D Array with first row set to 0:\n", array_4x4)


5x5 Array of sequential numbers:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Middle 3x3 Sub-array:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
2D Array with first row set to 0:
 [[0 0 0 0]
 [6 8 3 4]
 [5 7 9 7]
 [3 2 2 5]]


 Mathematical Operations
 Compute the mean, median, and standard deviation of a randomly generated array of
1000 elements.
 Perform a dot product of two 1D arrays of length 4.

In [36]:
random_array = np.random.random(1000)
mean_value = np.mean(random_array)
median_value = np.median(random_array)
std_deviation = np.std(random_array)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)
array_x = np.array([1, 2, 3, 4])
array_y = np.array([4, 3, 2, 1])

dot_product = np.dot(array_x, array_y)
print("Dot Product:", dot_product)


Mean: 0.5054871592944462
Median: 0.5086035435759784
Standard Deviation: 0.29221694769011464
Dot Product: 20


 Broadcasting
 Create a 5x5 array of zeros and add a 1D array of shape (5,) to each row of the 2D array
using broadcasting.
 Create a 3x3 array and subtract a scalar value from it.

In [41]:
zeros_array = np.zeros((5, 5))
array_1d_to_add = np.array([1, 2, 3, 4, 5])

broadcast_result = zeros_array + array_1d_to_add

print("5x5 Array after broadcasting:\n", broadcast_result)

array_3x3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
scalar_value = 5

subtracted_result = array_3x3 - scalar_value

print("3x3 Array after subtracting scalar value:\n", subtracted_result)



5x5 Array after broadcasting:
 [[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
3x3 Array after subtracting scalar value:
 [[ 5 15 25]
 [35 45 55]
 [65 75 85]]


 Aggregations
 Calculate the sum of all elements in a 6x6 array with random values between 1 and 10.
 Find the index of the maximum value in a 1D array of 50 random values.

In [42]:
import numpy as np

array_6x6 = np.random.randint(1, 11, (6, 6))
sum_elements = np.sum(array_6x6)

print("6x6 Array with random values:\n", array_6x6)
print("Sum of all elements:", sum_elements)
array_1d_50 = np.random.random(50)
max_index = np.argmax(array_1d_50)

print("1D Array of 50 random values:\n", array_1d_50)
print("Index of the maximum value:", max_index)


6x6 Array with random values:
 [[ 7  5  7  7  9 10]
 [ 1  3  8  2  9  2]
 [ 4  3  4  6  2  8]
 [ 7  9  8  5 10  5]
 [ 1  9  2  2  5  2]
 [ 3  5  3  4  1  7]]
Sum of all elements: 185
1D Array of 50 random values:
 [0.38288335 0.53216847 0.89227868 0.45567074 0.75248701 0.3756363
 0.49078022 0.44472654 0.77257552 0.07140169 0.53865323 0.98183053
 0.90472526 0.98242403 0.08732461 0.21153028 0.49562625 0.5810315
 0.20007634 0.0567118  0.12473628 0.38976376 0.76877156 0.74358557
 0.52700809 0.86757021 0.20591924 0.39674029 0.9498095  0.03508589
 0.14066798 0.11538998 0.41428793 0.57290325 0.97309504 0.7415482
 0.73566175 0.23471562 0.78561264 0.63854064 0.95595956 0.36603885
 0.44910277 0.94710956 0.54259743 0.91337727 0.86017301 0.66319765
 0.25264262 0.77227461]
Index of the maximum value: 13


 Reshaping and Flattening
 Reshape a 1D array of 12 elements into a 3x4 array.
 Flatten a 4x4 array into a 1D array.

In [43]:
array_1d_12 = np.arange(12)
array_3x4 = array_1d_12.reshape(3, 4)

print("1D Array of 12 elements:", array_1d_12)
print("Reshaped to 3x4 Array:\n", array_3x4)
array_4x4 = np.random.randint(1, 20, (4, 4))
flattened_array = array_4x4.flatten()

print("4x4 Array:\n", array_4x4)
print("Flattened to 1D Array:", flattened_array)


1D Array of 12 elements: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4x4 Array:
 [[19  6 18  7]
 [ 3 17  6  7]
 [ 1 18  6  4]
 [ 6 11 15 18]]
Flattened to 1D Array: [19  6 18  7  3 17  6  7  1 18  6  4  6 11 15 18]


 Linear Algebra
 Solve a system of linear equations represented by a 2x2 matrix and a 2x1 vector.
 Compute the inverse of a 3x3 matrix (if it is invertible).

In [44]:
coefficients = np.array([[2, 3], [5, 1]])
constants = np.array([8, 7])

solution = np.linalg.solve(coefficients, constants)

print("Solution for the system of equations:", solution)

matrix_3x3 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

# Check if the matrix is invertible by checking if the determinant is not zero
if np.linalg.det(matrix_3x3) != 0:
    inverse_matrix = np.linalg.inv(matrix_3x3)
    print("Inverse of the 3x3 Matrix:\n", inverse_matrix)
else:
    print("The matrix is not invertible.")



Solution for the system of equations: [1. 2.]
Inverse of the 3x3 Matrix:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


 Statistical Analysis

 Create a 100x100 array of random numbers and calculate the correlation coefficient
matrix.
 Compute the cumulative sum of a 1D array of 20 elements.

In [48]:
array_100x100 = np.random.random((100, 100))
correlation_matrix = np.corrcoef(array_100x100)

print("Correlation Coefficient Matrix:\n", correlation_matrix)
array_20 = np.arange(20)
cumulative_sum = np.cumsum(array_20)

print("1D Array of 20 elements:", array_20)
print("Cumulative Sum:", cumulative_sum)


Correlation Coefficient Matrix:
 [[ 1.         -0.05806753 -0.03831468 ...  0.05953777  0.16603374
   0.09513458]
 [-0.05806753  1.         -0.06708271 ...  0.06409675  0.17250847
  -0.03190772]
 [-0.03831468 -0.06708271  1.         ...  0.07787748  0.08678444
   0.07097143]
 ...
 [ 0.05953777  0.06409675  0.07787748 ...  1.          0.26605195
   0.07264119]
 [ 0.16603374  0.17250847  0.08678444 ...  0.26605195  1.
  -0.03623988]
 [ 0.09513458 -0.03190772  0.07097143 ...  0.07264119 -0.03623988
   1.        ]]
1D Array of 20 elements: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Cumulative Sum: [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]


 Advanced Indexing
 Create a 4x4 matrix and use boolean indexing to set all elements greater than 5 to -1.
 Generate a 2D array of shape (5, 5) and use advanced indexing to extract specific rows
and columns based on conditions.



In [51]:
matrix_4x4 = np.random.randint(1, 10, (4, 4))
matrix_4x4[matrix_4x4 > 5] = -1

print("4x4 Matrix after setting elements > 5 to -1:\n", matrix_4x4)

array_5x5 = np.random.randint(1, 10, (5, 5))
condition = array_5x5 > 4
extracted_elements = array_5x5[condition]

print("Original 5x5 Array:\n", array_5x5)
print("Elements greater than 4:\n", extracted_elements)


4x4 Matrix after setting elements > 5 to -1:
 [[ 3 -1  3 -1]
 [-1 -1  3 -1]
 [ 5  2 -1  2]
 [ 3 -1  3  3]]
Original 5x5 Array:
 [[5 9 2 6 3]
 [7 3 8 1 8]
 [2 4 4 8 1]
 [9 6 7 1 6]
 [6 5 6 2 8]]
Elements greater than 4:
 [5 9 6 7 8 8 8 9 6 7 6 6 5 6 8]
